name: My firsttt Actions
on:
push:
jobs:
first-job:
runs-on: ubuntu-latest
strategy:
matrix:
node-version: [18, 20]
steps:
- name: Checkout Repo
uses: actions/checkout@v4
- name: Adding Node
uses: actions/setup-node@v6
with:
node-version: ${{matrix.node-version}}
- name: print welcome message
run: echo "Hello Devops"
- name: Print Node Version
run: node -v
- name: List repo files
run: ls -la
