name: My first Actions

on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Welcome Message
        run: echo "Hello DevOps"

      - name: Print Node Version
        run: node -v

      - name: List Repo Files
        run: ls -la
      - name: Cache npm packages
        uses: actions/cache@v4
        with:
         path: ~/.npm
         key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
         restore-keys:
           npm-cache-${{runner.os}}-
      - name: print message
        run: echo "Caching Demo"
